// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ngeozydfuodsxxqlqwlh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5nZW96eWRmdW9kc3h4cWxxd2xoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwNTk2MjcsImV4cCI6MjA1OTYzNTYyN30.xDC48_TwVdJbfBjvW17zu7a1oDXDg7OqeO3apQr6GLM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);